### ISSUE TITLE
Output should be in excel format

### ISSUE THREAD

**Issue by chameerawijebandara** [chameerawijebandara/Vehicle-Counter#1]
- For one day one excel file
- Each row represent 15min intervals in a day
- Columns {time interval, available video time(0-15min), vehicle count in Lane #1, ..., Total vehicle count}
- Each row with partial video time is colored (Orange)
- Each row with no video time is colored (Red)

**Comment by chameerawijebandara** [comment]
![capture](https://cloud.githubusercontent.com/assets/1333039/8335119/4442a94c-1ab9-11e5-8afd-39fb8b586776.PNG)
Cannot build the system

**Comment by randikaprabudda** [comment]
Doesn't quite sure about the error. Output in excel format is now up and running.

**Comment by chameerawijebandara** [comment]
It's OK I'll check it.
