### ISSUE TITLE
Build a standlannnnnng executable for testing

### ISSUE THREAD

**Issue by chameerawijebandara** [chameerawijebandara/Vehicle-Counter#4]

**Comment by randikaprabudda** [comment]
opencv_ts248d.lib(opencv_ts_pch.obj) : error LNK2038: mismatch detected for
'_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in BasicExcel.obj

this error keeps coming. do you have any clue about it. i tried many things

**Comment by chameerawijebandara** [comment]
Clean and rebuild the solution

**Comment by randikaprabudda** [comment]
​
 Vehicle-Counter.rar
https://docs.google.com/file/d/0B5kNTa1aqNKRU2tJcmlVVXNaMmM/edit?usp=drive_web
​ error eka gana txt file ekak thyenawa aiya. araken push karanna ba e site
ekata uneble to access kiyala kiyanwa.

**Comment by randikaprabudda** [comment]
Aiya here's the two headers and source files as you asked..

On Mon, Jun 8, 2015 at 8:03 PM, Randika prabudda <randikaprabudda1@gmail.com

> wrote:
> 
> ​
>  Vehicle-Counter.rar
> https://docs.google.com/file/d/0B5kNTa1aqNKRU2tJcmlVVXNaMmM/edit?usp=drive_web
> ​ error eka gana txt file ekak thyenawa aiya. araken push karanna ba e
> site ekata uneble to access kiyala kiyanwa.
>

**Comment by chameerawijebandara** [comment]
where?

**Comment by randikaprabudda** [comment]
I've attached them with the mail

**Comment by chameerawijebandara** [comment]
Can you please send them again.

**Comment by randikaprabudda** [comment]
Building in the release mode is now solved

**Comment by chameerawijebandara** [comment]
Good
