### ISSUE TITLE
Customer feedback 

### ISSUE THREAD

**Issue by chameerawijebandara** [chameerawijebandara/Vehicle-Counter#6]
Please check this feedback and identify what we can improve.
1. Its not shifting from box marking frame to the app frame once boxes are marked (basically stuck there), but counting is happening due to some reason. So please fix this ASAP in order to try more videos and to give better feedback.
2. Please improve TEST button function (this is not working yet, but happy to see this working since its important)
3. Need to see final output in EXCEL 
4. And please improve box drawing tool (sometimes it works, some times it doesn't)
   These are the major comments as per now. 
   Your quick response to item 1 is highly appreciated.

**Comment by chameerawijebandara** [comment]
@randikaprabudda  @HBMDDS  what is this first comment. Is it fixed now?

**Comment by randikaprabudda** [comment]
Request for the Excel file is fixed now.
We are complicated about the function of test button. Not sure what action
it should perform.

**Comment by chameerawijebandara** [comment]
It should do a test run.

**Comment by chameerawijebandara** [comment]
@randikaprabudda 
You can send someone to fix this to traffic lab anytime. One of my RA (Madawa-0713009901) will assist.

**Comment by randikaprabudda** [comment]
aiya is there anyway to include a license for the libraries i used. it says
that it contains a license. But hard to understand do i need to include
that license in the exe or does it get automatically included. i think the
license problem is what creates a error when using the exe. here's the link
for that license.

http://www.codeproject.com/info/cpol10.aspx

**Comment by randikaprabudda** [comment]
Ah aiya error eka harigyada. Ignore the above msg

**Comment by chameerawijebandara** [comment]
I think this issue can class now
